# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: AFFINITY
email: 
description: > # this means to ignore newlines until "baseurl:"
  By Teens
  
  
baseurl: "/home/" # the subpath of your site, e.g. /blog
url: "https://affinitystories.ca" # the base hostname & protocol for your site

#sidebar
default-image: webjeda-logo-big.jpg # If there is no featured image in a post then this image will be showed. Also on all pages this image will be showed. Use a 500x250 image.

#footer

built-by: Jerry Zhou

copyright:
   name: Jerry Zhou
   link: 

# Build settings
markdown: kramdown
permalink: /:title/
paginate: 100
paginate_path: /page:num/

# Tracker
analytics: UA-83979019-1

# Comments
disqus: no
disqus-shortname: 

#social
facebook: https://www.youtube.com/watch?v=9SKOC24-obE&t=11s 
quora: 
twitter: about
github: https://github.com/jerryzhou196/MayorsChallengeWebsite
email: jerryz2@learn.cssd.ab.ca

#facebook like box
fb-like-box: yes
fb-app-id: 549480635219583
fb-page-url: https://www.facebook.com/webjeda/
fb-page-title: webjeda

# Sass style
sass:
  style: compressed

# Ruby Gems
plugins: [jekyll-paginate, jekyll-seo-tag]


